#support.yml

apiVersion: apps/v1
kind: Deployment
metadata:
        name: support
        labels:
                app: support
spec:
        replicas: 2
        selector:
                matchLabels:
                        app: support
        template:
                metadata:
                        labels:
                                app: support
                spec:
                        containers:
                                - name: support
                                  image: snehajain0310/support:12
                                  ports:
                                          - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: support
spec:
  selector:
    app: support
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
